src/accounts/urls.py
from django.urls import path

from .views import login_user, signup, logout_user

app_name = "accounts"
urlpatterns = [
	path("login/", login_user, name="login_user"),
	path("signup/", signup, name="signup"),
	path("logout/", logout_user, name="logout_user"),
]

src/blog/urls.py
from django.urls import path
from .views import index, publier_article, detail_article, commenter, modifier_article


app_name = "blog"
urlpatterns = [
	path('', index, name="index"),
	path('publier-article/', publier_article, name="publier-article"),
	path('modifier-article/<slug:slug>/', modifier_article, name="modifier-article"),
	path('article/<slug:slug>/', detail_article, name="detail-article"),
	path('commentaire/<slug:slug>/', commenter, name="comment-article"),
]

src/mysite/urls.py
from django.urls import path
from .views import index, a_propos, cv, services, projets, contact, commander_service

app_name = "mysite"

urlpatterns = [
    path("", index, name="index"),
    path("qui-suis-je/", a_propos, name="a_propos"),
    path("cv/", cv, name="cv"),
    path("services/", services, name="services"),
    path("projets/", projets, name="projets"),
    path("contact/", contact, name="contact"),
    path("commander-un-site/", commander_service, name="commander-service"),
]

src/portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

app_name = "portfolio"
handler404 = "mysite.views.page_not_found_view"


# handler404 = 'myapp.views.page_not_found_view'


def seo(request):
    return render(request, "seo/google779eb3315ac6f149.html")


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls"), name="site"),
    path('blog/', include("blog.urls"), name="blog"),
    path('accounts/', include("accounts.urls"), name="accounts"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/common/base.html
{% load static %}
<html lang="fr">
<head>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abel">

    <link rel="alternate" href="https://codeangel.pythonanywhere.com" hreflang="fr-FR">

    <link rel="stylesheet" href="{% static 'blog/prism/prism.css' %}">
    <script src="{% static 'blog/prism/prism.js' %}"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel=
            "stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>CodeANGEL | {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png"
          href="{% static 'mysite/img/logo_transparent.png' %}"/>

    <link rel="stylesheet" href="{% static 'mysite/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mysite/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    {% block style %}{% endblock %}

    <style>
        .row {
            margin: 0;
        }

        #menu {
            position: sticky;
            top: -220px;
            left: 0;
            width: 100%;
            transition: top 0.3s;
        }

        #menu.show {
            top: -1px;
        }


    </style>
</head>
<body id="{% block bodyId %}generic{% endblock %}" style="">

<header class="">
    {% block header %}
        <div class="container-fluid container-md" style="background-color: #042a2b">
            <div class="row">
                <div class="col-sm-6 offset-sm-1 mt-5">
                    <h1 class="m-0">
                        <a href="{% url 'mysite:index' %}" class="text-decoration-none" style="color:
                #8D0033">
                            <img src="{% static 'mysite/img/logo_transparent.png' %}"
                                 alt="mon logo" class="col-4" style="width: 40px; height: auto;
                                padding: 0">
                            <span class="col-8 p-0">CODEANGEL</span>
                        </a>
                    </h1>
                    <small style="font-size: medium">Conception/Développement/Logiciel</small>
                </div>
                <div class="col-sm-3 offset-sm-1">
                    <h3><a href="/media/pdf/MALLE_Moussa_CV.pdf"
                           download="MALLE-MOUSSA-CV.pdf"><i
                            class="glyphicon glyphicon-download"></i> CV</a></h3>
                    <h3><a href="javascript:void(0)" id="shareButton">Partagez</a></h3>
                </div>
            </div>
        </div>
    {% endblock %}
</header>
<main>
    {% block menu %}
        <section id="menu" style="z-index: 1">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="navbar navbar-expand-lg border-white fs-2 bg-white">
                            <button class="navbar-toggler" data-toggle="collapse" type="button"
                                    data-target="#Nav" aria-controls="Nav" aria-expanded="false"
                                    aria-label="Toggle navigation"><span
                                    class="glyphicon glyphicon-menu-hamburger"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="Nav">
                                <ul class="nav nav-tabs border-0 flex-column flex-md-row">
                                    <li class="nav-item"><a href="{% url 'mysite:index' %}"
                                                            class="nav-link">Accueil</a></li>
                                    <li class="nav-item dropdown">
                                        <a href="javascript:void(0)"
                                           class="nav-link dropdown-toggle"
                                           data-bs-toggle="dropdown">A Propos</a>
                                        <ul class="dropdown-menu fs-3 fw-bold border-white"
                                            style="background-color: #042a2b">
                                            <li>
                                                <a class="dropdown-item text-primary link-danger text-uppercase"
                                                   href="{% url 'mysite:cv' %}">Mes
                                                    Talents</a></li>
                                            <li><a
                                                    class="dropdown-item text-primary link-danger text-uppercase"
                                                    href="{% url 'mysite:projets' %}">Mes
                                                Projets</a></li>
                                        </ul>
                                    </li>
                                    <li
                                            class="nav-item"><a href="{% url 'mysite:services' %}"
                                                                class="nav-link">Mes
                                        Services</a></li>
                                    <li
                                            class="nav-item"><a href="{% url 'blog:index' %}"
                                                                class="nav-link">Mon
                                        Blog</a></li>
                                    <li class="nav-item"><a href="{% url 'mysite:contact' %}"
                                                            class="nav-link">Mon Contact</a></li>
                                    <li class="nav-item"><a
                                            href="{% url 'mysite:commander-service' %}"
                                            class="nav-link">Demander service</a></li>
                                    {% if user.is_authenticated and user.is_superuser %}
                                        <li class="nav-item"><a href="{% url 'admin:index' %}"
                                                                class="nav-link">Admin</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
    {% endblock %}
    <section class="contenu">
        <div class="container-fluid container-md">
            {% block contenu %}{% endblock %}
        </div>
    </section>
</main>
<footer>
    <div class="conainer">
        <div class="row">
            <div class="col-md-10 offset-md-1 fs-3 text-center">
                <hr>
                <a href="#">Informations</a> -
                <a href="#">Mentions Legales</a> -
                <a href="{% url 'mysite:contact' %}">Contacts</a>
                <br>
                <br>
                <p><a href="https://wa.me/+22379376132/?text=Contats Depuis CodeANGEL.COM...">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                         fill="currentColor"
                         class="bi bi-whatsapp" viewBox="0 0 16 16">
                        <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
                    </svg>
                    Whatsapp</a>
                    <a href="mailto:mallemoussa091@gmail.com"
                       class="contact-what" download="" style="display: inline-block;
                               margin-left: 10px"><i
                            class="glyphicon glyphicon-envelope"></i>Gmail</a>
                    <a href="tel:+22379376132"
                       class="contact-what" style="display: inline-block;
                               margin-left: 10px"><i
                            class="glyphicon glyphicon-earphone"></i>+223 79 37 61 32</a>
                </p>
                <p>(c) 2023 Conception et realisation par MALLE Moussa. Tous droits reserves.</p>
            </div>
        </div>
    </div>
</footer>

<script>

    (function () {
        let suite_presentation = document.getElementsByClassName("suite-presentation");
        let lire_suite = document.getElementsByClassName("lire-suite");

        function debloquer_la_suite() {
            for (let t = 0, c = lire_suite.length; t < c; t++) {
                lire_suite[t].addEventListener("click", function () {
                    voir_l_etat(t)
                })
            }
        }

        function voir_l_etat(i) {
            if (suite_presentation[i].style.display === "block") {
                suite_presentation[i].style.display = "none"
                lire_suite[i].innerHTML = "Lire plus"
            } else {
                suite_presentation[i].style.display = "block"
                lire_suite[i].innerHTML = "Lire moins"
            }
        }

        debloquer_la_suite()
    })();

    function share(shareButton, titre, url) {

        shareButton.addEventListener('click', () => {
            navigator.share({
                title: titre,
                url: url
            })
                .then(() => console.log('Partage réussi !'))
                .catch((error) => console.error('Erreur lors du partage :', error));
        });
    }

    let share1 = document.getElementById("shareButton")
    share(share1, "Votre bussiness merite une informatisation !", "https://codeangel.pythonanywhere.com")
    let prevScrollpos = window.scrollY;
    window.onscroll = function () {
        let currentScrollPos = window.scrollY;
        if (prevScrollpos > currentScrollPos) {
            document.getElementById("menu").classList.add("show");
        } else {
            document.getElementById("menu").classList.remove("show");
        }
        prevScrollpos = currentScrollPos;
    };

    // initialisation du prism pour la coloration syntaxique du code python et bien plus encore
    Prism.highlightAll();

</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

src/templates/common/base_blog.html
{% extends 'common/base.html' %}

{% block menu %}
{% endblock %}

{% block header %}
    <div class="container-fluid p-0 container-lg">
        <div class="row">
            <div class="col-md-12 p-0">
                <nav class="navbar navbar-dark bg-dark  justify-content-between navbar-expand-lg">
                    <div class="col-12 col-sm-6 col-md-4">
                        <h1 class="m-0">
                            <a href="{% url 'mysite:index' %}" class="text-decoration-none" style="color:
                #8D0033">
                                <img src="/media/common/logo_transparent.png"
                                     alt="mon logo" class="col-4" style="width: 40px; height: auto;
                                padding: 0">
                                <span class="col-8 p-0">CODEANGEL</span>
                            </a>
                            <small
                                    style="font-size: medium; display: block; color: white">Conception/Développement
                                /Logiciel</small>
                        </h1>
                    </div>
                    <div class="col-12 mt-3 col-sm-6 col-md-4">
                        <nav class="navbar navbar-expand-lg">
                            <button class="navbar-toggler" data-target="#Nav2"
                                    data-toggle="collapse" type="button" aria-controls="Nav2"
                                    aria-expanded="false">
                                <span class="glyphicon glyphicon-list"> Menu</span>
                            </button>
                            <nav class="navbar-collapse collapse" id="Nav2">
                                <ul class="navbar-nav">
                                    <li
                                            class="nav-item"><a href="{% url 'blog:index' %}"
                                                                class="nav-link">
                                        Accueil</a></li>
                                    <li class="nav-item dropdown">
                                        <a href="#" class="nav-link dropdown-toggle"
                                           data-toggle="dropdown"
                                           role="button">
                                            Catégories</a>
                                        <div class="dropdown-menu">
                                            <a href="#" class="dropdown-item">développement web &
                                                mobile</a>
                                            <a href="#" class="dropdown-item">L'IA</a>
                                            <a href="#" class="dropdown-item">Programmation en
                                                général</a>
                                            <a href="#" class="dropdown-item">Autres</a>
                                        </div>
                                    </li>
                                    {% if user.is_authenticated %}
                                        <li class="nav-item"><a href="#" class="nav-link">Notice</a>
                                        </li>
                                        <li class="nav-item"><a href="#" class="nav-link">Profil</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </nav>
                    </div>

                    <div class="col-12 mt-3 col-sm-12 col-md-4 text-center">
                        <form action="" method="post" class="form-inline p-md-3 ps-2">
                            {% csrf_token %}
                            <input type="search" class="form-control" name="search"
                                   placeholder="rechercher un article">
                            <input class="btn btn-outline-info" type="hidden" value="Rechercher">
                        </form>
                    </div>
                </nav>

            </div>
        </div>
    </div>
{% endblock %}

{% block contenu %}
    <div class="row">
        {% if not user.is_authenticated %}
            <div class="col-12">
                <h2 class="text-warning"><a href="{% url 'accounts:signup' %}">Créer un compte</a>
                    ou
                    <a href="{% url 'accounts:login_user' %}">Connecter vous</a> Pour publier vos
                    propres articles</h2>
            </div>
        {% else %}
            <div class="col-5 m-0">
                <h2>{{ user.first_name }} {{ user.last_name|upper }} ({{ user.username }})</h2>
            </div>
            <div class="col-5 offset-2 text-right">
                <h2 class="d-inline"><a href="{% url 'blog:publier-article' %}"
                                        class="btn btn-primary btn-lg">Publier un
                    article</a></h2>
                <h2 class="d-inline"><a href="{% url 'accounts:logout_user' %}"
                                        class="btn btn-danger btn-lg">Me déconnecter</a>
                </h2>
            </div>
        {% endif %}
    </div>
    {% block suite-contenu %}{% endblock %}
{% endblock %}