src/blog/urls.py
from django.urls import path
from .views import index, publier_article, detail_article, commenter, modifier_article


app_name = "blog"
urlpatterns = [
	path('', index, name="index"),
	path('publier-article/', publier_article, name="publier-article"),
	path('modifier-article/<slug:slug>/', modifier_article, name="modifier-article"),
	path('article/<slug:slug>/', detail_article, name="detail-article"),
	path('commentaire/<slug:slug>/', commenter, name="comment-article"),
]

src/portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

app_name = "portfolio"
handler404 = "mysite.views.page_not_found_view"


# handler404 = 'myapp.views.page_not_found_view'


def seo(request):
    return render(request, "seo/google779eb3315ac6f149.html")


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls"), name="site"),
    path('blog/', include("blog.urls"), name="blog"),
    path('accounts/', include("accounts.urls"), name="accounts"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.utils.text import slugify
from portfolio.settings import AUTH_USER_MODEL
from django.db import models

# Create your models here.

User = AUTH_USER_MODEL


class Commentaires(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	content = models.TextField()

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name = "Commentaire"
		verbose_name_plural = "Les Commentaires"


class Categories(models.Model):
	nom = models.CharField(max_length=100, verbose_name="Nom de la catégorie")
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.nom)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.nom

	class Meta:
		verbose_name = "Catégorie"
		verbose_name_plural = "Les Catégories"


class Articles(models.Model):
	titre = models.CharField(max_length=100, verbose_name="Titre")
	slug = models.SlugField(null=True)
	img = models.ImageField(
		upload_to="articles_pictures/", verbose_name="Image d'illustration"
		)
	content = models.TextField()
	date_creation = models.DateTimeField(auto_now_add=True, auto_now=False)
	categorie = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name="Catégorie")
	commentaire = models.ManyToManyField(Commentaires, null=True, blank=True)
	auteur = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.titre)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.titre

	class Meta:
		verbose_name = "Article"
		verbose_name_plural = "Les Articles"

src/blog/forms.py
from django import forms
from .models import Articles


class ArticleForm(forms.ModelForm):
	class Meta:
		model = Articles
		fields = ("titre", "categorie", "content", "img")
		widgets = {
			'content': forms.Textarea(attrs={'class': 'content'})
		}

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .forms import ArticleForm
from .models import Articles, Categories, Commentaires
from accounts.models import AccountsAuth


# Create your views here.


def index(request):
	cats = Categories.objects.all()
	articles = Articles.objects.all().order_by("-date_creation")
	return render(request, "blog/index.html", {"cats": cats, "articles": articles})


def publier_article(request):
	if request.user.is_authenticated:
		form = ArticleForm(request.FILES)
		user = request.user
		if request.method == "POST":
			form = ArticleForm(request.POST, request.FILES)
			if form.is_valid():
				article = form.save(commit=False)
				article.auteur = user
				article.save()
				return redirect("blog:index")
			return render(request, "blog/publier_article.html", {"form": form})
		return render(request, "blog/publier_article.html", {"form": form})

	return redirect("accounts:login_user")


def modifier_article(request, slug):
	if request.user.is_authenticated:
		user = request.user
		article = get_object_or_404(Articles, slug=slug)
		if request.POST:
			if article.auteur == user:
				form = ArticleForm(request.POST, request.FILES, instance=article)
				if form.is_valid():
					formm = form.save(commit=False)
					formm.auteur = user
					form.save(commit=True)
					return redirect("blog:index")
		form = ArticleForm(instance=article)
		return render(request, "blog/modifier_article.html", {"form": form})
	return redirect("accounts:login_user")


def detail_article(request, slug):
	article = get_object_or_404(Articles, slug=slug)
	comments = article.commentaire.all()
	auteur = article.auteur
	return render(
		request, "blog/detail-article.html", {
			"article": article, "comments": comments,
			"auteur": auteur
		}
		)


def commenter(request, slug):
	if request.method == "POST":
		content = request.POST["comment"]
		if content != "":
			user = request.user
			commentaire = Commentaires(content=content, user=user)
			commentaire.save()
			article = get_object_or_404(Articles, slug=slug)
			article.commentaire.add(commentaire)
			article.save()
	return redirect(reverse("blog:index"))

src/templates/blog/detail-article.html
{% extends 'common/base_blog.html' %}

{% block title %}Detail{% endblock %}
{% block style %}
    <style>
        @media only screen and (max-width: 768px) {
            .img-mobile {
                width: 100%;
                height: auto;
            }
        }

        .card-title {
            text-align: center;
            margin-top: 20px;
            font-weight: bold;
            font-size: 1em;
        }

    </style>
{% endblock %}

{% block suite-contenu %}
    <div class="row">
        <div class="col-12">
            <img src="{{ article.img.url }}" style="object-fit: cover;"
                 alt="photo d'ullustration" class="rounded img-mobile">
            {% autoescape off %}
                <h1 class="card-title">{{ article.titre }}</h1>
                <br>
                <div class="content">{{ article.content }}</div>
                <br>
                <p class="text-right">Article publié par <span
                        class="fw-bold">{{ article.auteur.username|upper }}</span>
                    le
                    <span class="fst-italic fw-bold">{{ article.date_creation }}</span></p>
            {% endautoescape %}
        </div>
        {% if user.is_authenticated %}
            <div class="col-12">

                <p class="inline-group"><a href="javascript:void(0)" id="share3"><span
                        class="glyphicon glyphicon-share"></span>Partager</a>
                    {% if user == auteur %} <a class="btn btn-warning btn-lg"
                                               href="{% url 'blog:modifier-article' article.slug %}">Modifier
                        cet
                        article</a>
                    {% endif %}</p>
                <form action="{% url 'blog:comment-article' article.slug %}" class="form-inline"
                      method="post">
                    {% csrf_token %}
                    <textarea class="form-control contact-input" name="comment"></textarea>
                    <input class="form-control btn btn-primary" type="submit" value="commenter">
                </form>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="text-uppercase text-black-50">Les commentaires</h1>
            {% for comment in comments %}
                <dl>
                    <dt>{% if comment.user.username %}{{ comment.user.username }}{% else %}NON
                        IDENTIFIE{% endif %}
                    </dt>
                    <dd class="ms-3">{{ comment.content }}</dd>
                </dl>
            {% endfor %}
        </div>

    </div>
{% endblock %}

{% block script %}
    <script>
        let share3 = document.getElementById("share3")
        share(share3, "Les articles de codeangel", "https://codeangel.pythonanywhere.com/blog/")

        // Supposons que vous ayez un élément avec une classe "content" contenant votre texte
        let contentElement = document.querySelector('.content');

        // Utilisez jQuery pour rechercher toutes les occurrences de '**' dans le contenu
        $(contentElement).html(function (index, oldHtml) {
            return oldHtml.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
        });
        $(contentElement).html(function (index, oldHtml) {
            return oldHtml.replace(/#(.*?)#/g, '<strong style="font-size: ' +
                '40px">$1</strong>');
        });
    </script>
{% endblock %}

src/templates/blog/index.html
{% extends "common/base_blog.html" %}
{% block bodyId %}blog{% endblock %}
{% block title %}Blog{% endblock %}

{% block suite-contenu %}

<div class="row">
    {% for article in articles %}
    <div class="col-md-4">
        <div class="card">
            <img src="{% if article.img %}{{ article.img.url }}{% endif %}"
                 alt="Image d'illustration"
                 class="card-img-top">
            <div class="card-body">
                {% autoescape off %}
                <h1 class="card-title">{{ article.titre }}</h1>
                <p class="card-text">{{article.content|truncatewords:20}}</p>
                <a href="{% url 'blog:detail-article' article.slug %}"
                   class="card-link link-primary">Voir en detail</a>
                <p>par <span class="fw-bold">{{article.auteur.username|upper}}</span> le
                    <span class="fst-italic fw-bold">{{article.date_creation}}</span></p>
                {% endautoescape %}
            </div>
        </div>
        <p class="inline-group"><a href="javascript:void(0)" id="share2"><span
                class="glyphicon glyphicon-share"></span>
            Partager</a></p>

    </div>
    {% endfor %}
</div>

{% endblock %}

{% block script %}
<script>
    let share2 = document.getElementById("share2")
    share(share2, "Les articles de codeangel", "https://codeangel.pythonanywhere.com/blog/")
</script>
{% endblock %}

src/templates/blog/modifier_article.html
{% extends "common/base_blog.html" %}
{% block title %}publier-article{% endblock %}
{% block style %}
<style>
  .errorlist li{
    color: red;
  }
</style>
{% endblock %}

{% block contenu %}
  <h1>Publier un article</h1>
<div class="col-md-6 offset-md-3">
  <form action="" method="post" class="text-black" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <p>
      <input type="submit" value="Modifier"
             class="form-control bg-primary btn btn-lg fs-1 fw-bold" style="height: 50px">
    </p>
  </form>
</div>
{% endblock %}

src/templates/blog/publier_article.html
{% extends "common/base_blog.html" %}
{% block title %}publier-article{% endblock %}

{% block contenu %}
  <h1>Publier un article</h1>
{% endblock %}