src/blog/urls.py
from django.urls import path
from .views import index, publier_article, detail_article, commenter, modifier_article


app_name = "blog"
urlpatterns = [
	path('', index, name="index"),
	path('publier-article/', publier_article, name="publier-article"),
	path('modifier-article/<slug:slug>/', modifier_article, name="modifier-article"),
	path('article/<slug:slug>/', detail_article, name="detail-article"),
	path('commentaire/<slug:slug>/', commenter, name="comment-article"),
]

src/mysite/urls.py
from django.urls import path
from .views import index, a_propos, cv, services, projets, contact, commander_service

app_name = "mysite"

urlpatterns = [
    path("", index, name="index"),
    path("qui-suis-je/", a_propos, name="a_propos"),
    path("cv/", cv, name="cv"),
    path("services/", services, name="services"),
    path("projets/", projets, name="projets"),
    path("contact/", contact, name="contact"),
    path("commander-un-site/", commander_service, name="commander-service"),
]

src/portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

app_name = "portfolio"
handler404 = "mysite.views.page_not_found_view"


# handler404 = 'myapp.views.page_not_found_view'


def seo(request):
    return render(request, "seo/google779eb3315ac6f149.html")


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls"), name="site"),
    path('blog/', include("blog.urls"), name="blog"),
    path('accounts/', include("accounts.urls"), name="accounts"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/mysite/models.py
from django.core.validators import RegexValidator
from django.db import models
from django_countries.fields import CountryField


# Create your models here.


class Clients(models.Model):

	options_profil = (
		("entreprise", "Entreprise"),
		("particulier", "Particulier")
	)

	last_name = models.CharField(max_length=50, verbose_name="Nom du client")
	first_name = models.CharField(max_length=50, verbose_name="Prénom du client")
	profil = models.CharField(
		max_length=50, verbose_name="Status du client", choices=options_profil
	)
	tel = models.CharField(max_length=50, verbose_name='Numéro de télephone')
	email = models.EmailField(verbose_name="Adresse mail du client")

	class Meta:
		verbose_name = "Client"
		verbose_name_plural = "Les Clients"
		ordering = ["last_name"]


class Projects(models.Model):
	name = models.CharField(max_length=100, verbose_name="Projets", )
	img = models.ImageField(upload_to="mysite/project_img/")
	describes = models.TextField(verbose_name="Description du projet")
	date = models.DateField(auto_now_add=True, auto_now=False)
	client = models.ForeignKey(Clients, on_delete=models.SET_NULL, null=True, blank=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Projet"
		verbose_name_plural = "Les Projets"


class Contact(models.Model):
	first_name = models.CharField(max_length=50, verbose_name="Prénom")
	last_name = models.CharField(max_length=50, verbose_name="Nom de famille")
	email = models.EmailField(verbose_name="Adresse mail")
	tel = models.CharField(verbose_name="Numéro de téléphone", max_length=50)
	msg = models.TextField()

	def __str__(self):
		return f"Message de {self.last_name}"

	class Meta:
		verbose_name = "Contact"
		verbose_name_plural = "Les Contacts"


class CommanderService(models.Model):

	# Informations clients

	nom_entreprise = models.CharField(max_length=200)
	raison_social = models.CharField(max_length=300)
	domaine_dactivite = models.CharField(max_length=200)
	adresse = CountryField()
	ville = models.CharField(max_length=200)

	# Personne à conatacter en charge du projet

	nom_personne = models.CharField(max_length=200)
	prenom_personne = models.CharField(max_length=200)

	regexTel = r'^(+){1}\d{2,4}\s?\d{4,10}$'
	tel = models.CharField(
		max_length=100, validators=[RegexValidator(
			regex=regexTel,
			message="Ce n'est pas un serieux numéro de télephone !"
			)]
		)
	email = models.EmailField()

	# Informations du projet
	options_forme_projet = (
		("creation_de_site", "Création de site"),
		("refonte_du_site", "Refonte de site"),
		("amelioration_du_site", "Amélioration du site"),
	)
	forme_du_projet = models.CharField(max_length=100, choices=options_forme_projet)
	refonte_true = models.URLField(blank=True)

	# objectifs du site
	options_nature_projet = (
		("site_vitrine", "Site vitrine"),
		("site_ecommerce", "Refonte de site"),
		("portail_info", "Amélioration du site"),
	)
	nature_du_projet = models.CharField(max_length=100, choices=options_nature_projet)

src/mysite/forms.py
from django import forms
from .models import Contact, CommanderService


class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = ["first_name", "last_name", "email", "tel", "msg"]


class CommanderServiceForm(forms.ModelForm):
	class Meta:
		model = CommanderService
		fields = "__all__"

src/mysite/views.py
from django.shortcuts import render, redirect
from .models import Projects, Clients, Contact
from .forms import ContactForm, CommanderServiceForm
from django.core.mail import send_mail
from blog.models import Articles
from django.core.paginator import Paginator

import os


# Create your views here.


def send_email(request, msg, from_email):
	subject = "Besoin d'aide depuis CodeANGEL.com"
	message = msg
	from_email = from_email
	recipient_list = ["code.angel.091@gmail.com"]
	send_mail(subject, message, from_email, recipient_list)


def index(request):
	articles = Articles.objects.all().order_by("-date_creation")[:3]
	return render(request, "mysite/index.html", {"articles": articles})


def a_propos(request):
	return render(request, 'mysite/a-propos.html')


def cv(request):
	dev = {
		"HTML/CSS/JS": 80,
		"python": 70,
		"django": 50,
		"Bootstrap": 50,
		"sql/sqlite/mysql": 40,
	}
	mod = {
		"merise": 70,
		"uml": 50
	}
	ver = {
		"git/github": 45,
	}

	return render(request, "mysite/cv.html", context={"dev": dev, "mod": mod, "ver": ver})


def services(request):
	base = "/media/mysite/services-pictures/"
	cartes = {
		"Création de sites web": (
			base + "web-site.png",
			"Nous concevons et développons des "
			"sites web professionnels et "
			"modernes  qui répondent aux besoins "
			"uniques  de nos clients.<br><br>Nos "
			"sites web sont conçus pour offrir une"
			" expérience utilisateur exceptionnelle"
			" et une navigation fluide."
		),
		"Applications web et mobiles sur mesure": (
			base + "app.png",
			"Applications web et mobiles sur mesure Nous développons des applications web et "
			"mobiles personnalisées qui répondent aux exigences spécifiques de votre entreprise. "
			"<br><br>Nos applications sont conçues pour fonctionner de manière transparente sur "
			"différentes plateformes et offrir une convivialité optimale."
		),
		"Référencement de site": (
			base + "seo.png",
			"Nous optimisons votre site web pour les moteurs de recherche afin d'augmenter sa "
			"visibilité en ligne. <br><br>Grâce à nos techniques de référencement avancées, "
			"nous vous aidons à attirer un trafic qualifié et à améliorer votre classement dans les "
			"résultats de recherche."
		),
		"Intégration et création d'applications desktop": (
			base + "app-desk.png",
			"Nous offrons des services d'intégration et de développement d'applications desktop "
			"puissantes et fonctionnelles. <br><br>Que ce soit pour automatiser des processus "
			"métier "
			"ou "
			"pour améliorer l'efficacité opérationnelle, nous sommes là pour vous aider."
		),
		"Conception de bases de données": (
			base + "db.png",
			"Nous concevons des bases de données robustes et sécurisées pour stocker et gérer "
			"efficacement vos données. <br><br>Notre expertise en conception de bases de données vous "
			"assure une gestion efficace de vos informations critiques."
		),
		"Refonte de l'existant": (
			base + "refonte-site.png",
			"Nous améliorons les aspects visuels de votre site ou d'application déjà existant(e)."
			"<br>En plus nous ajoutons de nouvelles fonctionnalités ou "
			"des améliorations techniques, telles que l'intégration de médias sociaux, l'ajout de "
			"fonctionnalités de commerce électronique, l'intégration d'un blog."
		)
	}

	return render(request, "mysite/services.html", context={"cards": cartes, })


def projets(request):
	list_projet = Projects.objects.all()
	return render(request, "mysite/projects.html", context={"projets": list_projet})


def contact(request):
	template = ""
	form = ContactForm()

	if len(request.POST) > 0:
		form = ContactForm(request.POST)

		if form.is_valid():
			form.fisrt_name = request.POST["first_name"]
			form.last_name = request.POST["last_name"]
			form.email = request.POST["email"]
			form.tel = request.POST["tel"]
			form.msg = request.POST["msg"]
			form.save()
			send_email(request, form.msg + "\nTel: " + form.tel, form.email)
			send_ok = "Merci !\nVotre message a bien été envoyé, vous serez contacté dans le " \
					  "meilleur délai"
			# return redirect("mysite:contact")
			template = "mysite/contact.html"
			return render(request, template, context={"msg_ok": send_ok})
		else:
			errors = "Veuillez bien remplir tous les champs !"
			template = "mysite/contact.html"
			return render(request, template, context={"errors": errors})
	else:
		template = "mysite/contact.html"
		context = {}
		return render(request, template, context)


def page_not_found_view(request, exception):
	return render(request, "common/404.html")


def commander_service(request):
	context = {}
	form = CommanderServiceForm()
	print()
	paginator = Paginator(form, 2)
	context['form'] = paginator.get_page(1)
	return render(request, "mysite/commander_service.html", context)

src/templates/mysite/a-propos.html
{% extends 'common/base.html' %}

{% block title %}Qui est-il?{% endblock %}
{% block bodyId %}a-propos{% endblock %}

{% block contenu %}
<div class="container">
    <div class="row fs-4">
        <div class="col-md-6 ligne row1">
            <div class="body">
                <h2>Qui suis-je</h2>
                <p>
                    hello evry body 🫡<br>je suis Moussa MALLE, connu dans le
                    monde du code sous le pseudonyme CodeANGEL. Je suis étudiant en
                    licence 2 informatique et passionné par le développement web.
                </p>
            </div>
            <div class="triangle triangle2"></div>
        </div>

        <div class="col-md-6 ligne row2">
            <div class="body">
                <h2>Mon Parcours</h2>
                <p>
                    Depuis que j'ai commencé mes études en informatique,
                    j'ai été captivé par le monde du développement web.
                    J'ai découvert que créer des sites et des applications web était non
                    seulement fascinant, mais aussi une façon puissante de donner vie à des
                    idées et de résoudre des problèmes.
                </p>
            </div>
            <div class="triangle triangle1"></div>
        </div>

        <div class="col-md-6 ligne row2">
            <div class="body">
                <h2>Mes compétances</h2>
                <p>
                    En tant que développeur web, j'ai acquis une solide
                    compréhension des langages de programmation tels que HTML
                    , CSS et JavaScript. J'ai également exploré des frameworks
                    populaires comme Django et des bibliothèques telles que
                    React.js. <br><br>
                    Je suis capable de concevoir des interfaces utilisateur
                    attrayantes et réactives, de créer des fonctionnalités
                    dynamiques et interactives, et de collaborer avec des
                    équipes pour développer des projets web de qualité.
                </p>
            </div>
            <div class="triangle triangle1"></div>
        </div>

        <div class="col-md-6 ligne row1">
            <div class="body">
                <h2>Mes projets</h2>
                <p>
                    Au cours de mes études et de mon temps libre, j'ai travaillé
                    sur divers projets web, allant de sites web personnels à des
                    applications plus complexes. J'ai également contribué à des
                    projets open source, ce qui m'a permis de développer mes
                    compétences et d'apprendre des meilleures pratiques de l'industrie.
                    <p><a href="{% url 'mysite:projets' %}">En savoir plus sur mes projets</a></p>
                    <br>Mon objectif est de
                    continuer à explorer de nouvelles
                    technologies et à développer des projets innovants qui
                    offrent une expérience utilisateur exceptionnelle.
                </p>
            </div>
            <div class="triangle triangle2"></div>
        </div>
        <div class="col-md-6 ligne row1">
            <div class="body">
                <h2>Ma vision</h2>
                <p>
                    En tant que développeur web, je crois en l'importance de
                    créer des solutions technologiques qui améliorent la vie des
                    utilisateurs. Je m'efforce de concevoir des applications
                    conviviales, accessibles et efficaces qui répondent aux besoins
                    des utilisateurs tout en respectant les normes de l'industrie.
                    <br><br>Je suis constamment à la recherche de nouvelles
                    opportunités de développement professionnel, de
                    collaboration et d'apprentissage pour continuer à
                    développer mes compétences et à contribuer au monde du web.
                </p>
            </div>
            <div class="triangle triangle1"></div>
        </div>
    </div>

</div>
{% endblock %}

src/templates/mysite/commander_service.html
{% extends 'common/base.html' %}

{% block title %}Commander Service{% endblock %}

{% block contenu %}
    <h1>Desolé ! cette page est en cours de développement !</h1>
    <p>Merci de faire un tour dans les prochains jours.</p>
{% endblock %}

src/templates/mysite/contact.html
{% extends "common/base.html" %}

{% block title %}Contact{% endblock %}

{% block bodyId %}contact{% endblock %}

{% block contenu %}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center fs-1" style="font-size: 24px">Nous contacter</h1>
        <p style="color: blue; font-weight: bold">Vous avez des
            questions, des
            suggestions
            ou besoin d'un
            service ?
            N'hésitez pas à nous contacter en utilisant le formulaire ci-dessous.
        </p>
        <form class="col-md-12" action="" method="post">
            {% csrf_token %}
            <hr>
            <p class="text-danger text-center">{% if errors %}{{errors}}{% endif %}</p>
            <p class="text-secondary text-center">{% if msg_ok %}{{msg_ok}}{% endif %}</p>
            <div class="col-md-4 offset-md-2">
                <div class="from-group">
                    <label for="name" class="form-label">Votre nom complet</label>
                    <div class="input-group">
                        <input name="first_name" type="text" id="name"
                               class="form-control contact-input"
                               placeholder="votre prénom">
                        <input name="last_name" type="text" id="last_name" class="form-control contact-input"
                               placeholder="votre nom">
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="form-label">Votre adresse mail</label>
                    <input name="email" type="email" class="form-control contact-input" id="email">
                </div>
                <div class="form-group">
                    <label for="tel" class="form-label">Votre contact (de préference
                        whatssap)</label>
                    <input name="tel" type="tel" class="form-control contact-input" id="tel">
                </div>
            </div>
            <div class="col-md-4">
                <label for="msg">Votre message</label>
                <textarea name="msg" id="msg" cols="30" rows="6"
                          class="form-control contact-input"></textarea>
            </div>
            <div class="col-md-12 text-center">
                <p class="mt-2">
                    <input type="submit" class="btn btn-primary fs-1" value="SOUMETTRE">
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/templates/mysite/index.html
{% extends "common/base.html" %}
{% load static %}

{% block title %}HOME{% endblock %}

{% block bodyId %}home{% endblock %}

{% block contenu %}

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-danger text-black fs-3">
            <div class="panel-heading"><h2><span class="glyphicon glyphicon-home"></span>
                Présentation</h2></div>
            <div class="panel-body align-items-center">
                <div class="col-sm-2">
                    <img src="{% static 'mysite/img/logo_transparent.png' %}" alt="Mon logo"
                         class="rounded-circle w-100 border-danger border border-2"
                         height="auto">
                </div>
                <div class="col-sm-10">
                    <p class="lead fs-2 fw-bold">Vous êtes à la recherche d'une
                        personne
                        compétante et
                        efficace pour réaliser vos projets web ?</p>
                </div>
                <div class="col-sm-12">
                    <hr>
                    <p class="">
                        Actuellement, je suis Etudiant en 2ème année Informatique, je suis
                        passionné par le développement informatique et c'est bien ce que
                        fais d'ailleurs, j'utilise ces compétances pour réaliser vos projets
                        web et mobile(sites et/ou applications web et mobiles).
                        <span style="display: none" class="suite-presentation">
                                <br>
                                Aujourd'hui, je fais:
                                <br><br>
                                Redaction cahier de charges <br>
                                Elaboration de votre design et integration précise <br>
                                Développement et programmation de votre projet <br>
                                Mise en ligne de votre projet <br>
                                Réflexion stratégique, statistique et reférencement <br>
                                Maintenance et mise à jour régulière <br>

                            </span>
                        <em class="text-primary lire-suite" style="cursor: pointer;">lire plus</em>

                    </p>
                </div>
                <div class="col-5">
                    <img src="{% static 'mysite/img/codeangel.png' %}" alt="Mon logo"
                         class="rounded img-thumbnail" width="100%">
                </div>
            </div>
        </div>
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2><span class="glyphicon glyphicon-bullhorn"></span> Actualités</h2>
            </div>
            <div class="panel-body">
                <h1 class="text-center fs-1 fw-bold">Les nouvelles articles, cliquez pour voir dans
                    le
                    blog</h1>
                {% for article in articles %}
                <div class="card">
                    {% autoescape off %}
                    <a href="{% url 'blog:detail-article' article.slug %}"
                       class="text-black fs-1 fw-bold text-center">
                        {% if article.img %}
                        <img src="{{ article.img.url }}" alt="image du projet {{article.nom}}"
                             class="rounded card-img" style="width: 100%; height: 100px;
                             object-fit: cover;">
                        {% endif %}
                        <div class="card-img-overlay" style="background-color:
                        rgba(255, 255, 255, 0.2)">
                            <div class="card-body">
                                <h1 class="card-title">{{article.titre}}</h1>
                            </div>
                        </div>
                    </a>
                    {% endautoescape %}
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div
                    class="panel-heading"><h2><span class="glyphicon glyphicon-user"></span> Qui
                suis-je ?</h2></div>
            <div class="panel-body">
                <div class="col-md-10 offset-md-1">
                    <h3 class="text-center fs-2 text-decoration-underline">En quelques
                        mots</h3>
                    <dl class="fs-4 dl-vertical mt-5">
                        <dt>Mes casquettes:</dt>
                        <dd class="ms-5 mb-4">Etudiant, Développeur web</dd>

                        <dt>Mes talents:</dt>
                        <dd class="ms-5 mb-4">De la redaction de cahiers de charges
                            jusqu'à la mise en
                            production du projet(site ou app web)
                        </dd>

                        <dt>Technologies:</dt>
                        <dd class="ms-5 mb-4">HTML/CSS/JS; Python/Django; Bootstrap; Conception
                            MERISE;
                            Modélisation UML; Algorithmique; SQL/MySQL/SQLite
                        </dd>

                        <dt>Passion:</dt>
                        <dd class="ms-5 mb-4">Coder coder coder...; Lecture, Ecouter de la
                            musique
                        </dd>
                        <dt>Vision:</dt>
                        <dd class="ms-5 mb-4">Contribuer au développement de
                            l'internet en géneral et du Web en particulier
                            .
                        </dd>
                    </dl>
                    <p class="text-center"><a href="{% url 'mysite:a_propos' %}"
                                              class="btn btn-lg"
                                              style="background-color:#042a2b; color: white">En
                        savoir
                        plus</a></p>

                </div>
            </div>
        </div>

    </div>
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading"><h2><span
                    class="glyphicon glyphicon-briefcase"></span> Expérience</h2></div>
            <div class="panel-body fs-4">
                <p class="fw-bold">
                    Je suis ravi de vous présenter mes
                    expériences en développement de sites web. En tant
                    que passionné du web, j'ai créé plusieurs sites qui
                    mettent en valeur mes compétences et ma créativité.
                    Aujourd'hui, je vais vous présenter trois de mes
                    réalisations les plus significatives : mon propre site, un site web pour un
                    restaurant et un site
                    de discussion.
                </p>

                <dl class="text-center suite-presentation" style="display: none">
                    <dt class="text-decoration-underline">Mon Site - Celui-ci 👌</dt>
                    <dd class="">J'ai conçu mon propre site portfolio pour
                        présenter mes compétences et mes projets. J'ai mis
                        l'accent sur une conception responsive, offrant une
                        expérience utilisateur fluide sur tous les appareils.
                        J'ai choisi un design épuré et moderne pour mettre en
                        valeur mes réalisations. J'ai utilisé des technologies
                        telles que HTML, CSS, JavaScript et même Bootstrap pour
                        développer ce site.
                    </dd>

                    <dt class="text-decoration-underline">Site Web Restaurant</dt>
                    <dd>J'ai eu l'opportunité de créer un site web pour un
                        restaurant local. J'ai travaillé en étroite collaboration
                        avec le propriétaire pour comprendre l'identité de
                        l'établissement et créer une présence en ligne qui
                        reflète son ambiance. J'ai développé un site web
                        attrayant et convivial, permettant aux clients de
                        réserver en ligne, de consulter le menu interactif,
                        de parcourir une galerie de photos et de lire les avis
                        des clients satisfaits. Le site a été développé en utilisant
                        des technologies telles que HTML, CSS/Bootstrap, JS et Python/DJANGO.
                    </dd>

                    <dt class="text-decoration-underline">Site De Discussion</dt>
                    <dd>Un autre projet passionnant que j'ai réalisé est la
                        création d'un site de discussion. J'ai voulu offrir aux
                        utilisateurs un espace en ligne pour échanger et partager des
                        idées sur des sujets spécifiques. J'ai développé une plateforme
                        avec des fonctionnalités telles que l'enregistrement des utilisateurs,
                        la création de discussions thématiques, la possibilité de commenter et
                        de partager du contenu, ainsi qu'une modération efficace. J'ai utilisé
                        des technologies comme JavaScript, Python/Django et MySql pour
                        construire
                        cette plateforme interactive.
                    </dd>
                </dl>
                <p class="text-right"><em class="text-primary lire-suite"
                                          style="cursor: pointer;">lire
                    plus</em></p>
            </div>
        </div>

    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading"><h2><span class="glyphicon glyphicon-earphone"></span>
                Contact</h2></div>
            <div class="panel-body" id="panel-body-contact">
                <div class="col-md-10 offset-md-1">
                    <address class="text-center">
                        <p><a href="{% url 'mysite:contact' %}"
                              class="btn btn-primary btn-lg">Me
                            contacter</a></p>
                        <p><a
                                href="https://wa.me/+22379376132/?text=Contats Depuis CodeANGEL.COM..."
                                class="contact-what">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                 fill="currentColor"
                                 class="bi bi-whatsapp" viewBox="0 0 16 16">
                                <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
                            </svg>
                            Whatsapp</a>
                            <a href="mailto:mallemoussa091@gmail.com"
                               class="contact-what" style="display: inline-block;
                               margin-left: 10px"><i
                                    class="glyphicon glyphicon-envelope"></i>Gmail</a>
                            <a href="tel:+22379376132"
                               class="contact-what" style="display: inline-block;
                               margin-left: 10px"><i
                                    class="glyphicon glyphicon-earphone"></i>+223 79 37 61 32</a>
                        </p>
                    </address>
                </div>
            </div>
        </div>
    </div>
</div>
{% block script %}
<script>
function getWidth(){
    let currentWidth = window.innerWidth
    if(currentWidth < 576){
        console.log("je suis dans xs")
    }
    else{
        console.log("dans du lg")
    }
}
// setInterval(() => getWidth(), 1000)


</script>
{% endblock %}

{% endblock %}

src/templates/mysite/projects.html
{% extends 'common/base.html' %}
{% block title %}Projets{% endblock %}
{% block bodyId %}projets{% endblock %}

{% block contenu %}
<div class="row">
    <div class="col-12 text-center">
        <h1>Permettez-moi de vous présenter quelques unes de mes réalisations.
            À travers mon parcours en informatique et mon expertise dans
            le domaine, j'ai réalisé plusieurs projets impressionnants qui démontrent
            ma créativité, ma maîtrise technique et mon engagement envers l'excellence.
        </h1>
    </div>
</div>
<div class="row">
    {% for projet in projets %}
        <div class="col-md-4 col-sm-3">
            <div class="card">
                <img src="{{ projet.img.url }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h2 class="card-title">{{projet.name}}</h2>
                    <p class="card-text">{{projet.describes}}</p>
                    <a href="" class="card-link btn btn-primary">Voir le projet</a>
                </div>
            </div>
        </div>
    {% empty %}
    <h3 class="text-danger">Pas de projet pour le moment</h3>
    {% endfor %}
</div>
{% endblock %}